baseurl = "https://programan.github.io/"
title = "Programan Website"
theme = "nix"
languageCode = "ja"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "Programan"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Programan"
  HeaderUsername = "hugo"
  HeaderHostname = "hugo"
  Email = "hoge@example123.com"
  About = "Github pagesの練習。コンテンツはHugoで出力"
  ProfilePicture = "/profile.jpg"
  SlackURL = "your_slack_invite_url"

